[package]
name = "cassis-cli"
version.workspace = true
edition.workspace = true

[dependencies]
cassis-client = { path = "../cassis-client" }
cassis-core = { path = "../cassis-core" }
cassis-iroh = { path = "../cassis-iroh" }
cassis-nostr = { path = "../cassis-nostr" }
cassis-onchain = { path = "../cassis-onchain" }
clap = { version = "4", features = ["derive"] }
futures = "0.3"
iroh = "0.35"
lowercase-hex = "0.1"
rustls = "0.23"
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
