[package]
name = "cassis-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"
env_logger = "0.11"
log = "0.4"
lowercase-hex = { version = "0.1", features = ["alloc"] }
rand = "0.8"
ritualistic = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
