[package]
name = "cassis-routing"
version.workspace = true
edition.workspace = true

[dependencies]
cassis-core = { path = "../cassis-core" }
log = "0.4.33"
ritualistic = "0.1.1"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "1.0.69"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
