[package]
name = "cassisd"
version.workspace = true
edition.workspace = true

[dependencies]
cassis-core = { path = "../cassis-core" }
cassis-iroh = { path = "../cassis-iroh" }
cassis-routing = { path = "../cassis-routing" }
env_logger = "0.11"
log = "0.4"
bip32 = { version = "0.5", default-features = false, features = ["secp256k1", "std"] }
bip39 = { version = "2.2.2" }
clap = { version = "4", features = ["derive"] }
hmac = "0.12"
iroh = "0.35"
lowercase-hex = "0.1"
ritualistic = "0.1.1"
rustls = "0.23"
sha2 = "0.10"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync"] }

[dependencies.cassis-cashu]
path = "../networks/cassis-cashu"
optional = true

[dependencies.cassis-fedimint]
path = "../networks/cassis-fedimint"
optional = true

[dependencies.cassis-arkade]
path = "../networks/cassis-arkade"
optional = true

[dependencies.cassis-rootstock]
path = "../networks/cassis-rootstock"
optional = true

[dependencies.cassis-liquid]
path = "../networks/cassis-liquid"
optional = true

[features]
ark = ["cassis-arkade"]
cashu = ["cassis-cashu"]
liquid = ["cassis-liquid"]
fedimint = ["cassis-fedimint"]
rootstock = ["cassis-rootstock"]
