[package]
name = "cassisd"
version.workspace = true
edition.workspace = true

[dependencies]
cassis-core = { path = "../cassis-core" }
cassis-iroh = { path = "../cassis-iroh" }
cassis-nostr = { path = "../cassis-nostr" }
cassis-onchain = { path = "../cassis-onchain" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }

[dependencies.cassis-cashu]
path = "../networks/cassis-cashu"
optional = true

[dependencies.cassis-fedimint]
path = "../networks/cassis-fedimint"
optional = true

[dependencies.cassis-ark]
path = "../networks/cassis-ark"
optional = true

[dependencies.cassis-rootstock]
path = "../networks/cassis-rootstock"
optional = true

[dependencies.cassis-liquid]
path = "../networks/cassis-liquid"
optional = true

[features]
ark = ["cassis-ark"]
cashu = ["cassis-cashu"]
liquid = ["cassis-liquid"]
fedimint = ["cassis-fedimint"]
rootstock = ["cassis-rootstock"]
